### ISSUE TITLE
Sporadical breaking behavior 

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#20]
After the last VSC update the debugger started acting up. Particularly when I set a breakpoint prior launch, then launch - it doesn't break right away. I need a random amount of page reloads to trigger the break. I've noticed no regularity: sometimes I need 2-3 reloads, sometimes 10-15.

Only errors in the log are 
```
  ERROR|003.107|TabActorProxy: No such actor "server1.conn0.child8/tab1"
  ERROR|003.108|FirefoxDebugSession: Failed attaching to tab: No such actor
```
and they only occur 1 time per launch and never on reload and IIRC they've been occurring before the issue so I doubt they are the direct culprit.

VSC team are [currently fiddling with node debuggers](/Microsoft/vscode/issues/3215#issuecomment-262281829). Maybe they did something to the interface?

BTW, regarding the linked issue. Do you have plans for excluding/skipping/hiding files/folders like the [Chrome Debug's ``experimentalLibraryCode``](/Microsoft/vscode-chrome-debug#other-optional-launch-config-fields) option in your extension?

Thanks.

**Comment by hbenl** [comment]
Thanks for the test case - at first I wasn't able to reproduce this issue but with the test case I eventually saw the same behaviour (although it happens less often on my machine). Please test with the latest release and tell me if the fix works for you as well.

The errors you saw in the log are indeed unrelated to this - they are caused by a weird behaviour that recent Firefox versions sometimes show directly after launching: Firefox tells the debug adapter that a new tab has been opened and then says the tab has been closed immediately after that. In the meantime the debug adapter sent a message to Firefox that it wants to attach to the tab and gets an error message back because the tab has already disappeared.

The feature described in the linked issue does indeed sound interesting, I will put it on my TODO list.

**Comment by Spown** [comment]
It got better, however it still never triggers breakpoints right after the launch. only after I reload the page in FF...

**Comment by hbenl** [comment]
Yes, reloading the page is still necessary - as explained in #7 this is due to a limitation of the Firefox debug protocol and therefore I don't think I can fix it.

**Comment by Spown** [comment]
>The feature described in the linked issue does indeed sound interesting, I will put it on my TODO list.

You probably know it already, but ``skipFiles`` ware just [implemented by node, node2 and Chrome debuggers](https://code.visualstudio.com/updates#_just-my-code-node-and-node2). So there is already some working code to pry into - hope it saves you some time.

**Comment by hbenl** [comment]
@Spown The latest version now supports `skipFiles`. It's only slightly different from the implementation in the Node and Chrome debuggers: it only supports glob patterns, so instead of `"file.js"` you'd have to write `"**/file.js"` and instead of `"folder"` you'd write `"**/folder/**"`.

**Comment by Spown** [comment]
Nice! Thank you very much, I'll test it as soon as possible!
