### ISSUE TITLE
Cleaning profiles after debug session

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#26]
following #10 

Yes, temp folder should be cleaned from time to time anyway, but the speed it gets trashed with profiles is just staggering. Especially if the temp folder is located on a SSD drive this becomes quite problematic. So maybe after stopping a session the profile that was just used could be deleted?

Also I would suggest not to create a new profile copy if the session was relaunched - only if it was a new start (i.e. stop->start). Instead the previous profile could be used until the session is decisively terminated. This would speed up the launch and ease the load on the drive. I think this should be the default behavior and there should be an option to force profile regeneration on every launch.

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/explorer_2017-01-15_19-22-19.png)

thank you.

**Comment by hbenl** [comment]
The adapter already tries to delete the temp profile folder - I know this doesn't work reliably (haven't looked into this yet), but in your case it seems to not work at all, so I'll try to find out why.

As for re-using the previous profile folder: I'm working on a re-attach flag for launch configurations: when it is set, Firefox will be kept running at the end of the debug session and will be re-attached to when starting the next session (this will also work when clicking the reload button in VS Code, as this simply stops the running session and starts a new one). In this case, the existing profile will be re-used of course.

**Comment by hbenl** [comment]
I have just published a new version containing the `reAttach` feature that I mentioned above.

**Comment by Spown** [comment]
I've noticed that without ``reAttach`` the adapter still spams profiles on both start and restart, but I've noticed that the older folders are like ~1/3 smaller in size and in file/subfolder count. I guess the adapter does try to clean up, but doesn't  really care... however with ``reAttach``, when I manually stop and close the FF window and relaunch manually - the older profiles stay fully intact (doesn't seem that it even tries to cleanup.)

Also a bit of a feedback&suggestion to the ``reAttach``: it is perfect for ``restart`` but when I hit ``stop`` I expect the FF window to be closed (and the profile regenerated) as well. However I can see how it can be useful for someone else/different scenarios, so maybe instead of/supplemental to ``reAttach: boolean`` you could make something like ``reAttach: true || false || "always" || "onReload" || "onStart" || "never"`` (with ``true/false`` being the same as ``"always"/"never"``)?

Thank you.

**Comment by hbenl** [comment]
* yes, with `reAttach` the debug adapter doesn't try to clean up the profiles anymore, simply because in general it isn't running when Firefox is stopped. I'll have to start another process with the sole purpose of watching the Firefox process and cleaning up when it exits. I haven't done this yet because [starting long-running processes from the debug adapter is surprisingly difficult](https://github.com/Microsoft/vscode/issues/22022)
* when I added the `reAttach` feature, I thought the stop-and-reattach-later scenario was the main use case and the restart scenario was just a nice side effect, because you could have essentially the same effect by using the reload button in Firefox. So I'd like to know why you prefer to use the restart button in VS Code - is it just so you don't have to switch between VS Code and Firefox windows or is there some other difference in debugging behaviour?

**Comment by Spown** [comment]
I didn't say I ideologically prefer one over another. I do use restart more often than FF reload partially because I'm used to; partially because many of sessions that I debug are POST requests and reloading the page prompts me to resend the data and in 2/3 of the cases it is not desirable; partially because when the process is paused it is faster to restart->switch_window than save->switch_window->reload; partially because I edit the code while running so I guess while I could save->resume(while probably stumbling over an error)->switch_window->reload, restart is again faster and it assures me that everything is started clean. When I don't edit the code and just inspecting the behavior (especially behavior shared over different pages and thus over different code files) or when I've edited the code while not running, but the FF window is still opened - the FF reload becomes more preferable. And this is in the projects I'm currently working on. More complex/simple ones may shift the proportion of using one option over the other. It is really only situational.

**Comment by hbenl** [comment]
Thanks for the feedback, I see that both options have advantages and drawbacks.
Unfortunately I think it's currently impossible to implement your proposal because I can't find out if the user pressed the stop or the restart button: in both cases VS Code sends the same event to the debug adapter to terminate it.

Back to the original issue: I think I have now found a way to reliably delete the temporary profile when Firefox is closed, so I'll add that to the next release.

**Comment by hbenl** [comment]
The temporary profiles are now reliably deleted, both with and without the `reAttach` option.
