### ISSUE TITLE
Don't touch LocalStorage

### ISSUE THREAD

**Issue by fehrenhuber** [hbenl/vscode-firefox-debug#32]
Hi, 
currently the debugger for firefox is useless for me, because the local storage data is not persisted  through  my debug sessions. As I persist the profiles of my applications users, I have to reenter all data for each debug session. This is not feasible!

**Comment by hbenl** [comment]
Currently the debug adapter creates a new temporary Firefox profile every time it launches Firefox, which is why any data stored in local storage in one debugging session will be gone in the next. I will add a configuration option to change this behaviour so that Firefox can work with a permanent debugging profile in which your local storage data will be kept.
In the meantime, there are some workarounds that you could use:
* use the `profile` or `profileDir` configuration option to specify a Firefox profile that contains some initial data for your application in local storage. This profile will be used as a template for the temporary debugging profiles, so all local storage data in that profile will be available in your debugging sessions. However, any changes made to that data during a debugging session will be gone in the next debugging session (because they will only be saved in the temporary profile and the next debugging session will use a new temporary profile).
* use the `reAttach` configuration option so that Firefox won't be terminated at the end of your debugging session. Since the debug adapter only creates a new temporary profile when launching Firefox (but not when reattaching to a running instance of Firefox), your local storage data will be kept between debugging sessions. However, as soon as you close Firefox manually, your local storage data will be gone and you'll have to start from scratch again.
* these options can also be combined

**Comment by hbenl** [comment]
I have just added the `keepProfileChanges` configuration option.
To use it you will need to set `profile` or `profileDir` to specify a Firefox profile - if you don't have a debugging profile for Firefox yet, just set `profileDir` to an empty or nonexistent directory and the profile will be created in this directory.
You will also need to set `reAttach` to `true` because there is no reliable way to shut down Firefox programmatically and the profile would get messed up eventually.
