### ISSUE TITLE
PathConversion: Can't convert url [...] to path

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#33]
I have ``"http?(s)://api-maps.yandex.ru/*"`` in my ``skipFiles``, still I get this
```
WARN |006.166|PathConversion: Can't convert url http://api-maps.yandex.ru/2.1/?lang=en_US&coordorder=longlat to path
WARN |006.519|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/map.js?callback=ym_map_fallback_75_url=httpsapi-mapsyandexru2150mapjs_filter=*_version=1491472497291&filter=*&version=1491472497291 to path
WARN |007.076|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/combine.js?load=0e9k0l:61()s9l2l1;1q)p)o1Q9r)r1I2a9o2e2g5K$K1)2;2I0b0f9y2r9t9v9C9D9F2x9w2u9A0y0r2G9H9L9M9O9P9S2O9T2R9V2V)t)u)v)w9W9Y2X22242$2_2(2,3g9492952q97989$9-9_9*9)912i2Q3a9,3c0m9@9;3e3k3m3o)B)x)y)A)C)E3t3v3A3C3E9i9j3K0R0W3X2@3x3M3P9z3T32349J38)L)P)N3$)R3.$a)S)G)K3*)T3,$c)U3;2Z0d3I3q3j3z$e3J0E0U0!-O$1$4$2$5$6$8$9-a$-$_$!$*)9)$)-$,$:$)$@)_).)!)*)($q))),):$j$z@y@A@B@C$Q$I$Z-c-d-f-g-k-l-m-o-w-x-y-C-D-F-G-p-r-t-u);-R-7-T-U-V)i-X-Y-0,b4g$f$h$k$m$n4e$o$r$s$u$v$x$y$C$E$F$H4a4l4n4o4r4t)V)W)X$T$B4h0O4u)Y)0)1)2)3)44w4y4A0:-I_a0J4C_m4$4R4F4H4L4N4P4T1a1f1l4;.g4q4i,1,2.h.k.l.m.n.o4z4J.p.r4Z1o5a5c5e5f5h5l5n1b4Y1A5S1G5.1V6x116U2h8f1u.s.t0t5r5v.u.v.w.x.y.A.B5p.F.L5y5C5E.S.R140N.T5L5w.U.V,3!D.Y.05N.$.-1w$A3f$G3l$O$S.;,4.@.q.j.i.z.Q.J.I5P.Z!a!b5R5T5V!c!d!e0A!f0F0P5X5Y5153!g!h!k,55556,6,7,8,9,$,-,_,.,!,*,(,),,,:,;,@,q!l0V581y5-5$5m1D5_1F5*1H:F!m:G:a:f:g:x:y:A:B:C:D:E:K:L:M:N:O:P!o:R:S:T:U:V:W:c:e:h!x!y!r:X:Y:0:1!A5:!n5@!w!B!C$3!E:2:4:3:55z!G:8:9:7:.!L!M!N!O!P!R!S!T!U:!:*!W!X!Y5Q!H:$:-5Z!K:_!V6a6f*l*m6k6l6m6e:J*D*n&callback_prefix=ymaps_loader to path
WARN |007.521|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/combine.js?load=*p$7*E*F*G096p*H*K6r6t6A*M*N*O6v6w6B6D*P1-00*R6F*S:Z;a;b;c;d;e2k0.*V6G6K6M6P6S6T6W6X*Y*0*1*2*43O0z*560;g;l623)633@1c*6*7*9*$*-*_***($($M3u$i$J5U656768$N$P6$6_6.6*6)6,6@6q6i6Q6J6Z2L$R1W1P1U!F107h13*:7t*;*@7v7x7A7C7D7F7H*q*j*i167K*z0w7O187P0D7U7T*Q*I;wqjqzq!q(q*j3q)q,q:j0j5j8j-j1j6j9j_j4;Dj2j7j$j.q;;Cq@irinisioitip;Eqn;HqF;FqIqZqoqpqrqsqtquqvqw;P;RjbjdjfjhjljnjpqyqAjrju;K;L;M;O;X;Y;2;3;4(d7W(e7072(s74(f;8;9;$;-(g;_;.(h(k;*;(;!(l(m75771_7$(n(o(p(r7__:(u7.(v7*7(7)7:7;7q;);,;:;;7z7Q7J7Z8a(x(y(w(B(C(D8b(E(F(G8d8e0K8g(K;@(L(M;j;i;z(O(P(R(S(T(U(W8h;Q8l8n8p8t(X8u(Y8x8A8B8F8H8E8C8K8M8N8O8R(0(1(2(3(4(5(6(78U8S8V8Y8283(-81(8(9($8586@f8889;J;Z@b@c@d@e@g8-8_8!8*8(8,8:(_8@8q8i8z0q8J(*9a8I9b(q(i(J(I(Z)b)c)d9e)e)f)g)hq-q$@m)l)m9f)n@n@o@p@r@t@u@v9h2o2B&callback_prefix=ymaps_loader to path
WARN |008.307|PathConversion: Can't convert url https://api-maps.yandex.ru/services/inception/?lang=en_US&iframe_id=7214&url=%2Fmap&api_version=2.1.50&mode=release&referer_host=prj.dev to path
WARN |008.338|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/combine.js?load=0B20033_3d4Q5b5g$w3R5j_tqhqkqQj!j*qlqJqmixiaq6j(iHiujZivj)ibiwiciFj,j@iyj:iGj;id366;6z7a7f7l7r7w7B7G7N_93-78_Q&callback_prefix=ymaps_loader to path
WARN |008.369|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/combine.js?load=0$4f3y01)70(4x0j4K1v5u1.1:7o1@7y7L3:1r1B3w-s3B-A3D-N3F-W-K3L-8---*-h3U_B3W_H31_R5I6d6h6o33_Yqgq0;V;Wq1q2q5q3q4q7(@(!&callback_prefix=ymaps_loader to path
WARN |008.418|PathConversion: Can't convert url https://api-maps.yandex.ru/2.1.50/combine.js?load=_d_f_0_1_4_6_7_8,U_!_*_)_,_;41434648!0!2!3!4!5!66c!8!Q:;:i:z:Q*g*h*k&callback_prefix=ymaps_loader to path
WARN |008.629|PathConversion: Can't convert url https://api-maps.yandex.ru/services/inception/inception-1480336775329.js to path
WARN |008.746|PathConversion: Can't convert url https://api-maps.yandex.ru/services/coverage/v2/?l=map&ll=17.72369400,46.82562400&z=4&lang=en_US&callback=jsonp_yandex_coverage__l_map_ll_17_72369400_46_82562400_z_4_lang_en_US&sign=1397552991 to path
```
Note that I have plenty external js linked on the page, but these are the only urls, that have query parts.

Thank you

**Comment by hbenl** [comment]
First of all, `skipFiles` is applied _after_ path conversion, so you will still see these warnings for files that are skipped.
But I guess your problem is not the warnings but rather that the files aren't skipped. Try using `**/api-maps.yandex.ru/**`. The `**` at the end is necessary because `*` would only match e.g. `map.js` but not `2.1.50/map.js` or `even/further/down/map.js`. The `**` at the beginning is necessary because glob patterns can't match `//` (which I just found out myself - yes, this means that the documentation is misleading and has to be updated).

**Comment by Spown** [comment]
``**/api-maps.yandex.ru/**`` doesn't work either. I mean they may be skipped still, but the warning persists. I would produce a test case, but I found so many things broken... more bugreports are coming.

**Comment by hbenl** [comment]
Yes, the warnings will always be there, even if the files are skipped. Maybe I should tone them down (INFO instead of WARN) because there's nothing wrong here, so warning about remote files that aren't part of your project is just confusing.

About the grayed call stack: it does show the last part of the url if you expand the debug pane a bit:
![screenshot_2017-04-11_21-13-44](https://cloud.githubusercontent.com/assets/16060807/24926457/eacbb8b0-1efb-11e7-9019-b5345b8b15b5.png)
![screenshot_2017-04-11_21-14-24](https://cloud.githubusercontent.com/assets/16060807/24926459/ed262082-1efb-11e7-9151-c00451b075b5.png)
VS Code hides the filename if there is not enough room for it.

But your test case alerted me to another bug - those functions in the call stack aren't all anonymous. In the next release it will look like this:
![screenshot_2017-04-11_21-18-08](https://cloud.githubusercontent.com/assets/16060807/24926586/61561d54-1efc-11e7-9b4c-6a6c35650812.png)
Not a big improvement in this case, but with non-minified (or sourcemapped) sources, this is useful information.

**Comment by Spown** [comment]
>About the grayed call stack: it does show the last part of the url if you expand the debug pane a bit:

no-no, what I meant was see this part [here](https://camo.githubusercontent.com/98d2423d7625544b316402b97f611bccca5d59b0/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f69643d30422d4f4a426f666d65684f3351334a705156525459556c43644655) 
```
[anonymous function]
v
V
```
this part is lacking [here](https://camo.githubusercontent.com/69c7442987d8c8fad034e4d4dd42cd00efb9f1c0/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f69643d30422d4f4a426f666d65684f335654644d646c566d62576851523030) - here it should be also present, but grayed out and the focus should still be on the ``[anonymous function] index.js 11`` i.e. 3 steps behind

**Comment by hbenl** [comment]
OK, I get it now. This is how `skipFiles` works: if an exception occurs in a source file that is skipped, the debugger will step out until it reaches a source file that isn't skipped. And since `skipFiles` is just configuring which source files are "blackboxed" by the Firefox debugger, I can't change this behaviour.

By the way, I have figured out why the tooltip that appears when the mouse hovers over the tab only shows "combine.js" - in the next release it will show the url minus the query part (i.e. "https://api-maps.yandex.ru/2.1.50/combine.js").

**Comment by hbenl** [comment]
I have just published another release that fixes the 2 bugs mentioned here that I could fix.
