### ISSUE TITLE
Breakpoints aren't being hit in reAttach isn't set to true

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#35]
No pause on breakpoints if ``reAttach`` is falsey. Not on the second page load not ever.

**Comment by hbenl** [comment]
I couldn't reproduce this. When you say the breakpoints aren't being hit on the second page load, do you mean you hit reload in Firefox or restart in VS Code? Because only hitting reload in Firefox will enable you to hit breakpoints that you couldn't hit on the first run.
If you still can't hit the breakpoints: What version of Windows are you on?

**Comment by Spown** [comment]
Win10x64. Ok, after restart it seems to work as intended. I'm closing the issue. Gonna watch out for this behaviour and keep a close eye on what's happening.
