### ISSUE TITLE
Couldn't find the Firefox executable

### ISSUE THREAD

**Issue by ivostoykov** [hbenl/vscode-firefox-debug#39]
Hello,
I was wondering how and where to set path_fo_FF? I'm using portable version. Couldn't find in the samples how to do it.

**Comment by hbenl** [comment]
Usually the Firefox executable is found automatically if Firefox was installed in the standard location.
If not, you can set the path with the `firefoxExecutable` property in your launch configuration. It's mentioned in the documentation and VS Code's intellisense in `launch.json` will also help you to find this and other configuration options.
![launch-json-intellisense](https://user-images.githubusercontent.com/16060807/26843908-0e151452-4af2-11e7-8830-6edc855ee9b3.png)

**Comment by ivostoykov** [comment]
Thank you! Works very well ;-)

**Comment by duzenko** [comment]
I stumbled into this today on a new Windows reinstall
FF 67.0 32bit was installed to default location C:\Users\a\AppData\Local\Mozilla Firefox
The plugin can't see it
Do I absolutely need to hardcode the path or the plugin should handle this situation?

**Comment by hbenl** [comment]
@duzenko I just tested this with FF 67.0 32bit on Windows 10 and Firefox was installed to `C:\Program Files (x86)\Mozilla Firefox` and the extension found it there. The location `C:\Users\<username>\AppData\Local\Mozilla\Firefox` is where Firefox usually keeps the profiles, but it's not the default install location.
If you configure the path for the Firefox executable, I recommend setting `firefox.executable` in your VS Code user settings (instead of setting `firefoxExecutable` in your `launch.json`) because it is a machine-specific setting.

**Comment by duzenko** [comment]
@hbenl 
Thank you for responding.
I uninstalled my copy of FF and downloaded the 32-bit installer again.
This time it seems to load from the Program Files. I'm not sure if it was a glitch in the particular installer I tried the last time or it's something FF does under certain conditions? I will post here if I see it happening again.

**Comment by hbenl** [comment]
> ...if the installer asked me if I want to install for current user or all users...

That's exactly what I suspected the 32-bit installer was doing after I read your initial comment. But it didn't ask me that question - perhaps an earlier version of the installer did that? It's also interesting that the installer for the 32-bit version looks and behaves different from the one for the 64-bit version.
