### ISSUE TITLE
Support for Add-Ons

### ISSUE THREAD

**Issue by mbarzeev** [hbenl/vscode-firefox-debug#4]
Hi,
First of all - Great work mate!

I would like to know if there is any plan to start supporting Firefox **Add-Ons** debugging as well?

Cheers

**Comment by hbenl** [comment]
Yes, that is actually high on my todo list, although I probably won't find the time to do it in the next couple of weeks. Which of the add-on types (WebExtensions, Add-on SDK aka Jetpack, or XUL overlays) do you intend to use?

**Comment by mbarzeev** [comment]
I'm using a XUL overlays.
Thanks

**Comment by blackwind** [comment]
Looking forward to Jetpack and WebExt support!

**Comment by hbenl** [comment]
Add-on debugging is here! Add-on SDK, WebExtensions and legacy add-ons (XUL overlays and restartless extensions) are all supported.
Please test it and let me know if it works for you.

**Comment by blackwind** [comment]
Working well with my Jetpack add-on. Cheers!

**Comment by blackwind** [comment]
A few things that could be improved:

* If Firefox is closed manually, the debugging session should stop. Currently, it doesn't.
* I keep getting an error on startup at line 19 of the SDK's `loader.js` because I don't have a `locales.json` file, and adding an empty one just triggers a different error. An option to suppress startup exceptions not in your code would be nice.
* When `loader.js` opens to show me the above error, hovering over the tab shows a tooltip like `\5\loader.js`. It'd be helpful if the actual path was displayed (in this case, `modules\commonjs\sdk\l10n\loader.js`), as the SDK includes several `loader.js` files.

**Comment by hbenl** [comment]
If have published a new version which
* terminates the debug session when Firefox is closed
* shows the full url of sources that don't correspond to local files in the project (`resource://gre/modules/commonjs/sdk/l10n/loader.js` in your case)
* fixes a bug with breakpoints in content scripts

As for suppressing the exception you get in `loader.js`: maybe I'll add new exception filters that let you specify separately whether you want to break on exceptions in your code and those not in your code.

**Comment by blackwind** [comment]
> As for suppressing the exception you get in loader.js: maybe I'll add new exception filters that let you specify separately whether you want to break on exceptions in your code and those not in your code.

When you have an update or a new issue for me to track, please do @mention me.

**Comment by hbenl** [comment]
@blackwind I have implemented a new configuration property called `skipFiles` which causes Firefox to "black box" any scripts that match the glob pattern(s) specified using this property.
So, for example, by adding `"skipFiles": [ "resource://**/sdk/**" ]` you can black box all scripts that are part of the add-on SDK, which means that the exception you were seeing in one of these files will be suppressed.

**Comment by blackwind** [comment]
Working as advertised. Cheers!

**Comment by blackwind** [comment]
I'm getting an error in `\296\webpack:\src\core\addonManager.js` when I open the Add-ons Manager in Firefox 53, and adding "webpack://**" to `skipFiles` didn't help. Bug?

**Comment by hbenl** [comment]
I couldn't reproduce this but I think I found the bug anyway.
Please try with the latest version of the debug adapter and tell me if your `skipFiles` expression works now.

**Comment by blackwind** [comment]
No luck. Same thing with the new version.

Note that after opening the Add-ons Manager, it takes 11 seconds on my machine to trigger the error. During this time, you can scroll the "Get Add-ons" view, but you can't select "Extensions" or any other views.

**Comment by blackwind** [comment]
If it helps, here's the exact version I'm running: 53.0a2 (2017-02-07) (64-bit)

**Comment by hbenl** [comment]
Thanks, I reproduced it now and will produce a fix (or rather a workaround, because I think that Firefox is sending me wrong information in this case) soon.

**Comment by hbenl** [comment]
Just published a new version which fixes the issue (at least in my setup).

**Comment by blackwind** [comment]
Well, the error doesn't pop up in VSCode anymore, but it still takes 11 seconds until I can interact with the Add-ons Manager. Since I'm working on debugging my add-on's options in the Add-ons Manager at the moment, the delay is a much, *much* bigger deal than the error.

Is there any other way you could approach working around the issue?

**Comment by hbenl** [comment]
I see. I don't think the delay has anything to do with the workaround, though, especially since that code is only executed once (and that just takes fractions of a second). I think the issue is rather that javascript execution seems to be significantly slower in Firefox when there is a debugger attached.
Does the code that you want to debug run in the Add-ons Manager tab? If not then I could add an option that the debug adapter should only attach itself to the first Firefox tab and you could open the Add-ons Manager in a second tab...

**Comment by blackwind** [comment]
It runs in the Add-ons Manager tab, yeah. Instead of using the SDK's `preferences` key in `package.json`, I bundle my own `options.xul` file and dynamically populate it via JS. Currently making some big changes to the way this is done for the next major version of my add-on.

My suspicion, based on you referring to the fix as a "workaround", was that the error is still being triggered in the Firefox debugger, thereby slowing it to a crawl, and then you simply ignore it if it matches `skipFiles` when it gets passed along to VSCode, whereas the errors matching my "resource://\*\*/sdk/\*\*" rule are skipped over by the Firefox debugger entirely. Note that the original error I was getting from the SDK (the one I'm filtering with "resource://\*\*/sdk/\*\*") doesn't delay execution in any way when it's skipped. Besides, no matter how much overhead the Firefox debugger incurs, there's no way a few lines of JS should be taking 11 seconds to execute on any computer built within the last 20 years.

If my suspicion is correct, perhaps a better approach would be to take the user's `skipFiles` and attempt to mangle any rules starting with "webpack://" to whatever format the Firefox debugger expects so matched items are skipped entirely.

**Comment by hbenl** [comment]
Your suspicion is half-correct: the debug adapter has 2 mechanisms for skipping files:
* telling Firefox to blackbox a source file if it matches any of the `skipFiles` patterns
* whenever an error occurs in a source file that matches any of the `skipFiles` patterns, the debug adapter tells Firefox to resume immediately

Obviously the first mechanism is much faster than the second (if a lot of errors are triggered, otherwise the difference shouldn't be noticeable) and it is usually sufficient - except if an error is triggered immediately after loading a file. In this case, the message telling Firefox to blackbox that file may not have reached Firefox in time, so Firefox doesn't know yet that this file should be blackboxed (the debug adapter can only tell Firefox to blackbox a file _after_ Firefox has loaded and hence started executing that file). This is the only reason for the second mechanism. This should never be a performance issue because the second mechanism will only be triggered once per source file at most. After that, the first mechanism will take care of skipping that file.

I've tried attaching Firefox' built-in debugger to the Add-ons Manager tab (using Tools -> Web Developer -> Connect...) and then reloading it - on my PC it took more than 15 seconds until I could interact with it. Without a debugger attached to that tab I could interact with it after less than a second. So I don't think I can fix the performance issue here :(

**Comment by blackwind** [comment]
Gotcha. Well, that's disappointing. :(
