### ISSUE TITLE
Inline scripts from generated html

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#50]
Probably related to #48 . Since the html is generated through the templater there is nothing corresponding to the url in the project dir. So on error I get a prompt to create the file

![](https://drive.google.com/uc?id=0B-OJBofmehO3Yk9xcTl0T3lsQVk)
And I will continue getting it on each step. 

If i accept - an empty file is created and the debugger will point to it, but since it's empty - it is not exactly useful...
![](https://drive.google.com/uc?id=0B-OJBofmehO3QjdOMXR4X0FPN1U)

I guess it should take a snapshot of the current html at the moment of the interruption state and open a tab with a virtual content of this snapshot.  Taking the initial html could be unhelpful since it is usual practice to inject scripts into head on startup, like AddThis or other libraries do

**Comment by hbenl** [comment]
When the debug adapter maps a url to a file in your workspace, it doesn't check if that file actually exists, it just sends the path to VS Code. That seems to be the core of the issue here, if the debug adapter knew that `http://xyz.dev/user/admin` does *not* correspond to a local file, then it would send the url to VS Code instead, VS Code would then fetch the html from Firefox via the debug adapter and display it as a virtual file (just as you described).
So I guess the debug adapter should either check if the file exists and if it doesn't, treat the url as one that can't be mapped to a local file.
Or I could add a way to configure urls that should not be mapped, perhaps something like this:
```
"pathMappings": [
    { "url": "http://xyz.dev/user/admin", "path": undefined }
]
```

**Comment by Spown** [comment]
The intelligent recognition would of coarse be better, but if it's not possible patteerns are better than nothing... Can launch.json even accept ``undefined``? I mean it's still a json, right? Maybe something like

```js
{ "url": "http://xyz.dev/user/admin", "path": "some/path", "ignore": true}
```

This would also let the user to preserve paths in the file when fiddling for the case when they will became mappable again.

**Comment by hbenl** [comment]
I realized that the automatic recognition does not cover all use cases, so I implemented the `pathMappings` solution instead. You can now set `path` to `null` (not `undefined` because I already use `null` as a possible configuration value in a different place and wanted to keep things consistent).
