### ISSUE TITLE
not breaking on error & printing it prematurely

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#56]
![](https://drive.google.com/uc?id=1xrDdtB5tGr7M_-ag4uWcJ_KHeXOMhuGn)

Stumbled upon this weird behavior:
1. an error is being printed as a string.
2. no breaking
3. the error seems to be accruing before/parallel to the debugger's session, since if I've set a breakpoint prior the expected error - the printing occurs even before the breakpoint is reached.
4. the debugger is still shown as ``running``, but nothing past the error's address seems to be reachable, i.e. any js past this point doesn't seem to be executed and no further breakpoints are being hit. so basically it looks like the break did happen but the debugger didn't react to it. The FF window doesn't freeze like it should while breaking either.
5. consistently doesn't happen on the clean session start - only while __restarting and reattaching__ to the already opend FF window. Sometimes on the first restart, sometimes on the second. But if I close the FF window and start the session ~~(or just ditch ``"reAttach": true``)~~ - everything will work fine. So basically it looks like some leaking or partial session decoupling.
    1.  If I drop ``"reAttach": true`` - it may or may not (50%/50%) do it right (proper break, no printing the error as a string) or print the error string.
![](https://drive.google.com/uc?id=1mxw41--MnB75QpRswtxtshQu5I4wMY0f)
I see no real consistency, but reloading (F5) the FF window seems to increase the chance of getting a faulty result, whereas if I only restart the debug session from VSC (which in no ``reAttach`` mode would close and relaunch FF) seems to be the most stable right now.
 
The extension was last updated 3 weeks ago, but the VSC [1.18.1 rolled a day ago](/Microsoft/vscode/milestone/57?closed=1) so I assume it is because of it. probably because of this [VSC#37880](/Microsoft/vscode/issues/37880).

Thank you.

**Comment by hbenl** [comment]
It looks like the debug adapter isn't attached to Firefox at the exact moment when the error is thrown - in this case the error is written to the Firefox console and when the debug adapter attaches to Firefox it asks for cached messages in the console and prints them to the VS Code console (so yeah, I think your guess that "the error seems to be accruing before to the debugger's session" is exactly right).
However, I couldn't reproduce this behaviour and can't think of a way how this can happen - especially since the error is triggered when the debug adapter asks Firefox to reload the page - this means that it _is_ attached to Firefox already when the error is thrown...
I will spend some more time in the next days trying to find out how this can happen, but if you have a test case for reproducing this, that would be super useful.

**Comment by hbenl** [comment]
In case you're still interested: I think I have found the problem and fixed it in the latest release.

**Comment by Spown** [comment]
Yeah, I haven't used FF in development since... But thank you anyway.
