### ISSUE TITLE
Vue.js component properties are shown as undefined.

### ISSUE THREAD

**Issue by theSdev** [hbenl/vscode-firefox-debug#65]
Hi. I'm using Vue.js 2.5.13 with Typescript and Webpack. Some properties on Vue component object are shown as undefined when I hover over them but are fine in debug console if I access them directly like this case:
![screenshot from hover on property](https://user-images.githubusercontent.com/24947508/37253366-24254b02-2546-11e8-89af-041ef82419e0.png)
but are not ok if I access their parent (this, the Vue object) and expand it:
![screenshot from debug console](https://user-images.githubusercontent.com/24947508/37253543-5977d5de-2548-11e8-8fd3-86a61d962325.png)
I wrote _some_ because others like $el are shown correctly, so I guess user-defined ones are those with the problem.
![screenshot from hover on property parent (Vue object, this)](https://user-images.githubusercontent.com/24947508/37253478-6cd10c32-2547-11e8-9185-337c70154872.png)
I don't have this issue with debugger for chrome either.
Thanks.

**Comment by hbenl** [comment]
The properties that are shown as "undefined" are accessor properties, i.e. their value is only accessible by calling a getter function. Since this getter function may have side-effects (i.e. it may change the state of the application), the Firefox debugger doesn't call it and hence doesn't show the value.

Here's what this situation looks like in Firefox' built-in debugger:
![screenshot_2018-03-11_18-28-07](https://user-images.githubusercontent.com/16060807/37256618-9152d5ca-255d-11e8-9a59-4f0f033a96ee.png)
The properties `links` and `object` are accessor properties that don't show their value.

In case you're wondering where these accessor properties come from (the shown source code clearly does not define them as accessor properties): I guess that Vue.js creates ES6 proxies for all components...

So why does it work in Chrome? Again, I can only guess: I think the Chrome debugger has the ability to do side-effect-free evaluations, meaning it can execute javascript code and then undo all modifications that this code did to the application state. In this way it is safe for the Chrome debugger to call the getter functions of accessor properties.

In the next version I will show "Getter & Setter" for these properties instead of "undefined", so that it's clearer why the value isn't visible.
Obviously that doesn't really solve the problem (only makes it slightly less confusing). I will investigate how the situation can be improved, maybe I will add a configuration property telling the debugger to evaluate getter functions, because the user thinks it is safe to do so.

**Comment by theSdev** [comment]
Thanks for the detailed response. Definitely looking forward for that option!

**Comment by hbenl** [comment]
I have just published a new version which allows you to execute the getters!

Currently this will only work for getters that are attached directly to the object, those that are attached to the prototype of the object can also be executed, but they will be executed with `this` set to the prototype, which will in general give a wrong result. I will fix this in a future version.

In my experiments all the getters that Vue.js generated were attached directly to the Vue components, so it should already work for you.
