### ISSUE TITLE
`-headless` for unit tests?

### ISSUE THREAD

**Issue by Misiur** [hbenl/vscode-firefox-debug#73]
Running unit tests spawns a lot of focus-stealing windows. Firefox has a `-headless` launch flag, but I can't seem to be able to force it correctly. I tried adding
`firefoxArgs: ['-headless']` [here](https://github.com/hbenl/vscode-firefox-debug/blob/5e537fece49148f1fc11c337a02c81c60cfdd67a/src/test/util.ts#L15) but that does not have an effect it seems. Any ideas?

**Comment by hbenl** [comment]
That's exactly what I do if I want to run the tests in headless mode (which is not often, because my window manager opens the windows in the background, and they don't steal the focus). It works for me on Linux and I just tried it on Windows 10 and it works there as well. I have no idea why it doesn't work for you.
