### ISSUE TITLE
JS file with query part in src

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#9]
``.js`` files aren't recognized if they are [referenced with some query part in the html](/Spown/vsc_ff_debug_test_webapp/commit/e84e550f810001ab55f3a9868c2566d0ac6ec876).

**Comment by hbenl** [comment]
That's because the debugger assumes that it's not the same file, since the browser also assumes this.
If you add another script tag in your example referencing `/static/js/index.js` (without a query part) and open it in the built-in Firefox debugger you will see that Firefox lists `index.js` and `index.js?v=1.0` separately in its list of script files. In this case the two files are the same but in general script files referenced with some query part could be (and usually are) server-generated, with the content of the generated script file depending on the query part of the url. So, assuming that `index.js?v=1.0` is the same as `index.js` would be wrong.

**Comment by Spown** [comment]
> assuming that index.js?v=1.0 is the same as index.js would be wrong.

In the browser's runtime context yes, it would, because every script tag after loading the url creates a separate source instance in memory indexed with it's url (or even if the url is an exact match, idunno). But debugger is a different story. Local file paths can't contain query part, because "?" is a special character. So if you ask me, I think the debugger should ignore query part when looking for the local files.

I'm not insisting, just saying it's a feature that wouldn't hurt to have.

**Comment by hbenl** [comment]
Yes, in some scenarios it could be helpful. But I would have to restructure some of the debug adapter code because it was written with the assumption that there is a 1-1 relationship between files known by the adapter and files known by Firefox and now it would be a 1-n relationship. So I don't intend to do it, at least not near-term.

**Comment by hbenl** [comment]
@Spown I have just released a new version that strips the query string from the url when converting it to a local file path! Apparently appending query strings to script urls is much more common than I thought, and the debug adapter is now able to handle a 1-n relationship of files known by the adapter to files known by Firefox.
